name: ♿ Accessibility Issue
description: Report an accessibility barrier or compliance issue
title: "[A11y]: "
labels: ["accessibility", "needs-triage", "priority-high"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an accessibility issue! These reports are crucial for making tkaria11y truly inclusive.
        
        **Note**: If this is a general bug, please use the Bug Report template instead.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have tested this with actual assistive technology (screen reader, etc.)
          required: true
        - label: I have checked if this affects multiple widgets or is widget-specific
          required: true
        - label: I have reviewed WCAG guidelines related to this issue
          required: false

  - type: dropdown
    id: user_group
    attributes:
      label: Affected User Group
      description: Which users are primarily affected by this accessibility issue?
      options:
        - Screen reader users (NVDA, JAWS, VoiceOver, etc.)
        - Keyboard-only users
        - Users with visual impairments
        - Users with motor impairments
        - Users with cognitive disabilities
        - Users with hearing impairments
        - Multiple user groups
        - All users
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Accessibility Severity
      description: How severe is this accessibility barrier?
      options:
        - Critical (completely blocks access)
        - High (major barrier, difficult workaround)
        - Medium (barrier exists, workaround available)
        - Low (minor accessibility improvement)
    validations:
      required: true

  - type: textarea
    id: barrier_description
    attributes:
      label: Accessibility Barrier Description
      description: Describe the accessibility barrier in detail
      placeholder: |
        Clearly describe:
        - What accessibility feature is not working
        - How it affects users with disabilities
        - What the user cannot accomplish
    validations:
      required: true

  - type: textarea
    id: assistive_tech
    attributes:
      label: Assistive Technology Testing
      description: What assistive technology did you test with?
      placeholder: |
        Please specify:
        - Screen reader: [e.g., NVDA 2023.1, JAWS 2023, VoiceOver macOS 13]
        - Browser/Platform: [if applicable]
        - Keyboard navigation: [tested/not tested]
        - Voice control: [tested/not tested]
        - Other tools: [magnification, etc.]
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Accessible Behavior
      description: What should happen for this to be accessible?
      placeholder: |
        Describe the expected accessible behavior:
        - What should screen readers announce?
        - How should keyboard navigation work?
        - What ARIA attributes should be present?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens that creates the accessibility barrier?
      placeholder: |
        Describe what actually happens:
        - What does the screen reader announce (or not announce)?
        - How does keyboard navigation fail?
        - What ARIA attributes are missing or incorrect?
    validations:
      required: true

  - type: textarea
    id: reproduction_code
    attributes:
      label: Code to Reproduce Issue
      description: Minimal code that demonstrates the accessibility issue
      render: python
      placeholder: |
        from tkaria11y import AccessibleApp
        from tkaria11y.widgets import AccessibleButton
        
        app = AccessibleApp(title="A11y Issue Demo")
        # Add code that demonstrates the accessibility issue
        app.mainloop()
    validations:
      required: true

  - type: dropdown
    id: wcag_guideline
    attributes:
      label: Related WCAG Guideline
      description: Which WCAG 2.1 guideline does this relate to?
      options:
        - "1.1 Text Alternatives"
        - "1.3 Adaptable (structure and relationships)"
        - "1.4 Distinguishable (color, contrast)"
        - "2.1 Keyboard Accessible"
        - "2.4 Navigable (focus, headings, labels)"
        - "3.2 Predictable"
        - "3.3 Input Assistance"
        - "4.1 Compatible (parsing, name/role/value)"
        - "Multiple guidelines"
        - "Not sure/Other"
    validations:
      required: false

  - type: textarea
    id: standards_reference
    attributes:
      label: Accessibility Standards Reference
      description: Reference to specific accessibility standards or guidelines
      placeholder: |
        If applicable, include:
        - WCAG 2.1 success criteria (e.g., 2.1.1 Keyboard)
        - ARIA Authoring Practices references
        - Platform accessibility guidelines
        - Screen reader documentation
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: Is there any workaround available?
      placeholder: |
        Describe any current workarounds:
        - Alternative ways to accomplish the task
        - Manual accessibility improvements
        - Third-party tools or solutions
    validations:
      required: false

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: Do you have suggestions for how to fix this accessibility issue?
      placeholder: |
        If you have ideas for fixing this:
        - ARIA attributes that should be added
        - Keyboard event handlers needed
        - Focus management changes
        - Screen reader announcement improvements
    validations:
      required: false

  - type: checkboxes
    id: testing_scope
    attributes:
      label: Testing Scope
      description: How extensively have you tested this issue?
      options:
        - label: Tested with multiple screen readers
        - label: Tested keyboard navigation thoroughly
        - label: Tested with high-contrast themes
        - label: Tested with different TTS voices
        - label: Tested on multiple operating systems
        - label: Consulted with users who have disabilities

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Environment information relevant to accessibility testing
      placeholder: |
        - OS: [e.g., Windows 11, macOS 13, Ubuntu 22.04]
        - Python version: [e.g., 3.9.7]
        - tkaria11y version: [e.g., 1.0.0]
        - Screen reader: [name and version]
        - TTS engine: [if relevant]
        - High-contrast mode: [enabled/disabled]
    validations:
      required: true

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: How does this issue impact the overall accessibility of applications using tkaria11y?
      placeholder: |
        Consider:
        - How many users might be affected?
        - Does this prevent core functionality access?
        - Are there legal/compliance implications?
        - Does this affect the framework's accessibility reputation?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information about this accessibility issue
      placeholder: |
        Include any:
        - Screenshots or recordings (if helpful)
        - Links to relevant accessibility resources
        - Feedback from users with disabilities
        - Related issues or discussions
    validations:
      required: false