name: ✨ Feature Request
description: Suggest a new feature or enhancement for tkaria11y
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make tkaria11y more accessible and useful for everyone.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: I have reviewed the roadmap (ROADMAP.md) to see if this is already planned
          required: true
        - label: I have considered if this aligns with tkaria11y's accessibility mission
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New Accessible Widget
        - Accessibility Enhancement
        - Theming/Visual Improvement
        - Developer Tools/CLI
        - Inspector Tool Enhancement
        - Migration Tool Enhancement
        - Documentation/Examples
        - Performance Improvement
        - API Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What accessibility need does it address?
      placeholder: |
        Describe the problem or accessibility barrier this feature would solve.
        For example: "Screen reader users cannot easily navigate complex data tables..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you envision this feature working. Include:
        - What the API might look like
        - How it would integrate with existing features
        - How it would improve accessibility
    validations:
      required: true

  - type: textarea
    id: api_example
    attributes:
      label: API Design Example
      description: If applicable, show how you imagine the API would work
      render: python
      placeholder: |
        # Example of how the new feature might be used
        from tkaria11y.widgets import AccessibleNewWidget
        
        widget = AccessibleNewWidget(
            parent,
            accessible_name="Example widget",
            new_feature_option=True
        )
    validations:
      required: false

  - type: textarea
    id: accessibility_benefits
    attributes:
      label: Accessibility Benefits
      description: How would this feature improve accessibility?
      placeholder: |
        Explain how this feature would benefit users with disabilities:
        - Screen reader users
        - Keyboard-only users
        - Users with visual impairments
        - Users with cognitive disabilities
        - Users with motor impairments
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Critical (addresses major accessibility barrier)
        - High (significantly improves user experience)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions or workarounds you've considered
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical ideas about implementation:
        - Which files might need changes
        - Dependencies that might be needed
        - Potential challenges or considerations
    validations:
      required: false

  - type: checkboxes
    id: standards
    attributes:
      label: Accessibility Standards
      description: Which accessibility standards or guidelines does this relate to?
      options:
        - label: WCAG 2.1 Guidelines
        - label: ARIA Authoring Practices
        - label: Section 508 Compliance
        - label: Platform-specific accessibility guidelines (Windows, macOS, Linux)
        - label: Screen reader compatibility
        - label: Not related to specific standards

  - type: textarea
    id: research
    attributes:
      label: Research/References
      description: Any research, examples, or references that support this request?
      placeholder: |
        Include any relevant:
        - Links to accessibility guidelines
        - Examples from other frameworks
        - User research or feedback
        - Academic papers or articles
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide accessibility expertise
        - label: I prefer to let others implement this

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about this feature request
      placeholder: Add any other context, mockups, or information that might be helpful
    validations:
      required: false