# tkaria11y.a11y_engine.pyi
# Type stubs for tkaria11y.a11y_engine

from typing import Any, Dict, List, Optional, Union, Callable, Tuple, Type, Set
import tkinter as tk
from tkinter import ttk
from enum import Enum
from abc import ABC, abstractmethod

class TTSEngine:
    def __init__(
        self: Any, rate: int = ..., volume: float = ..., voice_id: Optional = ...
    ) -> Any: ...
    def list_voices(self: Any) -> List: ...
    def set_rate(self: Any, rate: int) -> None: ...
    def set_voice(self: Any, voice_id: str) -> None: ...
    def set_volume(self: Any, volume: float) -> None: ...
    def shutdown(self: Any) -> None: ...
    def speak(
        self: Any, text: str, priority: str = ..., interrupt: bool = ...
    ) -> None: ...
    def stop(self: Any) -> None: ...
    def stop_current(self: Any) -> None: ...

atexit: Any
pyttsx3: Any
queue: Any

def shutdown_tts() -> None: ...
def speak(text: str, priority: str = ..., interrupt: bool = ...) -> None: ...

threading: Any
tk: Any
tts: Any
